In [66]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, accuracy_score
from sklearn.model_selection import GridSearchCV

In [67]:
startups = pd.read_excel('datasets/startup-expansion.xlsx')
startups

,Store ID,City,State,Sales Region,New Expansion,Marketing Spend,Revenue,Profit,ROMS,ROMS%
0,1,Peoria,Arizona,Region 2,Old,2601,48610,46009,1768.90,17.6890
1,2,Midland,Texas,Region 2,Old,2727,45689,42962,1575.43,15.7543
2,3,Spokane,Washington,Region 2,Old,2768,49554,46786,1690.25,16.9025
3,4,Denton,Texas,Region 2,Old,2759,38284,35525,1287.60,12.8760
4,5,Overland Park,Kansas,Region 2,Old,2869,59887,57018,1987.38,19.8738
...,...,...,...,...,...,...,...,...,...,...
145,146,Paterson,New Jersey,Region 1,New,2251,34603,32352,1437.23,14.3723
146,147,Brownsville,Texas,Region 2,New,3675,63148,59473,1618.31,16.1831
147,148,Rockford,Illinois,Region 1,New,2648,43377,40729,1538.10,15.3810
148,149,College Station,Texas,Region 2,New,2994,22457,19463,650.07,6.5007
149,150,Thousand Oaks,California,Region 2,New,2431,40141,37710,1551.21,15.5121

In [68]:
startups.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 10 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Store ID         150 non-null    int64
 1   City             150 non-null    object
 2   State            150 non-null    object
 3   Sales Region     150 non-null    object
 4   New Expansion    150 non-null    object
 5   Marketing Spend  150 non-null    int64
 6   Revenue          150 non-null    int64
 7   Profit           150 non-null    int64
 8   ROMS             150 non-null    float64
 9   ROMS%            150 non-null    float64
dtypes: float64(2), int64(4), object(4)
memory usage: 11.8+ KB

In [69]:
startups.describe()

,Store ID,Marketing Spend,Revenue,Profit,ROMS,ROMS%
count,150.000000,150.000000,150.000000,150.000000,150.000000,150.000000
mean,75.500000,2893.146667,39301.433333,36408.286667,1274.378133,12.743781
std,43.445368,367.862817,15465.753977,15435.408655,547.872035,5.478720
min,1.000000,1811.000000,15562.000000,12433.000000,395.620000,3.956200
25%,38.250000,2662.250000,21113.500000,18339.000000,637.380000,6.373800
50%,75.500000,2898.000000,42993.000000,40053.000000,1406.325000,14.063250
75%,112.750000,3111.500000,51145.500000,48163.250000,1660.317500,16.603175
max,150.000000,3984.000000,68828.000000,66388.000000,2720.820000,27.208200

In [70]:

startups.sample(10)

,Store ID,City,State,Sales Region,New Expansion,Marketing Spend,Revenue,Profit,ROMS,ROMS%
28,29,Waco,Texas,Region 2,Old,2483,39744,37261,1500.64,15.0064
57,58,Waterbury,Connecticut,Region 1,Old,3392,19350,15958,470.46,4.7046
97,98,Naperville,Illinois,Region 1,Old,2699,39856,37157,1376.70,13.7670
91,92,Augusta,Georgia,Region 1,Old,2676,47482,44806,1674.36,16.7436
26,27,Elizabeth,New Jersey,Region 1,Old,2557,45017,42460,1660.54,16.6054
148,149,College Station,Texas,Region 2,New,2994,22457,19463,650.07,6.5007
125,126,Sandy Springs,Georgia,Region 1,Old,2759,18942,16183,586.55,5.8655
78,79,Pueblo,Colorado,Region 2,Old,2928,19563,16635,568.14,5.6814
79,80,Costa Mesa,California,Region 2,Old,2275,41361,39086,1718.07,17.1807
146,147,Brownsville,Texas,Region 2,New,3675,63148,59473,1618.31,16.1831

In [74]:
grouped = startups.groupby(['City', 'State'])
print(grouped)
NumOfYes =0
NumOfNO=0
for (city, state), group in grouped:
    # Filter the group based on 'New Expansion' value if needed
    group = group[group['New Expansion'] == 'Old']
    if not group.empty:
        marketing_spend = group['Marketing Spend'].values[0]
        profit = group['Profit'].values[0]
        roms = group['ROMS'].values[0]
        
        print(f"City: {city}, State: {state}")
        
        if profit > 40053 and roms > 1274:
            NumOfYes = NumOfYes+1
            print(f"The Model suggests opening a new expansion in {city}, {state}")
        else:
            NumOfNO=NumOfNO+1
            print(f"The Model does not suggest opening a new expansion in {city}, {state}")
        
    else:
        print(f"No data found for City: {city}, State: {state}")
    
print(f"the number of suggestion for opening is  {NumOfYes}")
print(f"the number of suggestion for NOT opening is  {NumOfNO}")

<pandas.core.groupby.generic.DataFrameGroupBy object at 0x00000230A99AAE90>
City: Akron, State: Ohio
The Model suggests opening a new expansion in Akron, Ohio
City: Amarillo, State: Texas
The Model suggests opening a new expansion in Amarillo, Texas
City: Antioch, State: California
The Model does not suggest opening a new expansion in Antioch, California
City: Augusta, State: Georgia
The Model suggests opening a new expansion in Augusta, Georgia
City: Aurora, State: Illinois
The Model suggests opening a new expansion in Aurora, Illinois
City: Bellevue, State: Washington
The Model does not suggest opening a new expansion in Bellevue, Washington
City: Billings, State: Montana
The Model does not suggest opening a new expansion in Billings, Montana
City: Birmingham, State: Alabama
The Model suggests opening a new expansion in Birmingham, Alabama
City: Boulder, State: Colorado
The Model does not suggest opening a new expansion in Boulder, Colorado
City: Bridgeport, State: Connecticut
The Model suggests opening a new expansion in Bridgeport, Connecticut
City: Broken Arrow, State: Oklahoma
The Model does not suggest opening a new expansion in Broken Arrow, Oklahoma
No data found for City: Brownsville, State: Texas
City: Burbank, State: California
The Model does not suggest opening a new expansion in Burbank, California
City: Cambridge, State: Massachusetts
The Model does not suggest opening a new expansion in Cambridge, Massachusetts
City: Cape Coral, State: Florida
The Model suggests opening a new expansion in Cape Coral, Florida
City: Carrollton, State: Texas
The Model suggests opening a new expansion in Carrollton, Texas
City: Cedar Rapids, State: Iowa
The Model suggests opening a new expansion in Cedar Rapids, Iowa
City: Centennial, State: Colorado
The Model does not suggest opening a new expansion in Centennial, Colorado
City: Charleston, State: South Carolina
The Model does not suggest opening a new expansion in Charleston, South Carolina
No data found for City: Chattanooga, State: Tennessee
City: Clovis, State: California
The Model does not suggest opening a new expansion in Clovis, California
No data found for City: College Station, State: Texas
City: Columbia, State: South Carolina
The Model does not suggest opening a new expansion in Columbia, South Carolina
City: Columbus, State: Georgia
The Model suggests opening a new expansion in Columbus, Georgia
City: Concord, State: California
The Model does not suggest opening a new expansion in Concord, California
City: Coral Springs, State: Florida
The Model does not suggest opening a new expansion in Coral Springs, Florida
City: Costa Mesa, State: California
The Model does not suggest opening a new expansion in Costa Mesa, California
City: Daly City, State: California
The Model does not suggest opening a new expansion in Daly City, California
City: Davenport, State: Iowa
The Model does not suggest opening a new expansion in Davenport, Iowa
City: Davie, State: Florida
The Model suggests opening a new expansion in Davie, Florida
City: Dayton, State: Ohio
The Model does not suggest opening a new expansion in Dayton, Ohio
City: Denton, State: Texas
The Model does not suggest opening a new expansion in Denton, Texas
City: Des Moines, State: Iowa
The Model suggests opening a new expansion in Des Moines, Iowa
City: Edison, State: New Jersey
The Model does not suggest opening a new expansion in Edison, New Jersey
City: El Cajon, State: California
The Model does not suggest opening a new expansion in El Cajon, California
City: Elgin, State: Illinois
The Model does not suggest opening a new expansion in Elgin, Illinois
City: Elizabeth, State: New Jersey
The Model suggests opening a new expansion in Elizabeth, New Jersey
City: Elk Grove, State: California
The Model suggests opening a new expansion in Elk Grove, California
City: Everett, State: Washington
The Model does not suggest opening a new expansion in Everett, Washington
City: Fayetteville, State: North Carolina
The Model suggests opening a new expansion in Fayetteville, North Carolina
City: Fontana, State: California
The Model suggests opening a new expansion in Fontana, California
City: Fort Lauderdale, State: Florida
The Model suggests opening a new expansion in Fort Lauderdale, Florida
City: Fullerton, State: California
The Model does not suggest opening a new expansion in Fullerton, California
City: Gainesville, State: Florida
The Model suggests opening a new expansion in Gainesville, Florida
City: Garden Grove, State: California
The Model suggests opening a new expansion in Garden Grove, California
No data found for City: Glendale, State: California
City: Grand Prairie, State: Texas
The Model suggests opening a new expansion in Grand Prairie, Texas
City: Grand Rapids, State: Michigan
The Model suggests opening a new expansion in Grand Rapids, Michigan
City: Greeley, State: Colorado
The Model suggests opening a new expansion in Greeley, Colorado
City: Green Bay, State: Wisconsin
The Model does not suggest opening a new expansion in Green Bay, Wisconsin
City: Gresham, State: Oregon
The Model does not suggest opening a new expansion in Gresham, Oregon
City: Hampton, State: Virginia
The Model does not suggest opening a new expansion in Hampton, Virginia
City: High Point, State: North Carolina
The Model does not suggest opening a new expansion in High Point, North Carolina
City: Hillsboro, State: Oregon
The Model does not suggest opening a new expansion in Hillsboro, Oregon
City: Huntington Beach, State: California
The Model suggests opening a new expansion in Huntington Beach, California
City: Huntsville, State: Alabama
The Model suggests opening a new expansion in Huntsville, Alabama
City: Inglewood, State: California
The Model does not suggest opening a new expansion in Inglewood, California
City: Jackson, State: Mississippi
The Model suggests opening a new expansion in Jackson, Mississippi
No data found for City: Joliet, State: Illinois
City: Kent, State: Washington
The Model suggests opening a new expansion in Kent, Washington
City: Killeen, State: Texas
The Model suggests opening a new expansion in Killeen, Texas
City: Knoxville, State: Tennessee
The Model suggests opening a new expansion in Knoxville, Tennessee
City: Lafayette, State: Louisiana
The Model does not suggest opening a new expansion in Lafayette, Louisiana
City: Lakeland, State: Florida
The Model does not suggest opening a new expansion in Lakeland, Florida
City: Las Cruces, State: New Mexico
The Model does not suggest opening a new expansion in Las Cruces, New Mexico
City: Lewisville, State: Texas
The Model does not suggest opening a new expansion in Lewisville, Texas
City: Little Rock, State: Arkansas
The Model suggests opening a new expansion in Little Rock, Arkansas
City: Lowell, State: Massachusetts
The Model does not suggest opening a new expansion in Lowell, Massachusetts
City: Manchester, State: New Hampshire
The Model does not suggest opening a new expansion in Manchester, New Hampshire
City: McAllen, State: Texas
The Model suggests opening a new expansion in McAllen, Texas
City: Mesquite, State: Texas
The Model does not suggest opening a new expansion in Mesquite, Texas
City: Midland, State: Texas
The Model suggests opening a new expansion in Midland, Texas
City: Miramar, State: Florida
The Model suggests opening a new expansion in Miramar, Florida
City: Mobile, State: Alabama
The Model suggests opening a new expansion in Mobile, Alabama
City: Modesto, State: California
The Model suggests opening a new expansion in Modesto, California
City: Montgomery, State: Alabama
The Model suggests opening a new expansion in Montgomery, Alabama
City: Moreno Valley, State: California
The Model suggests opening a new expansion in Moreno Valley, California
City: Murfreesboro, State: Tennessee
The Model does not suggest opening a new expansion in Murfreesboro, Tennessee
City: Murrieta, State: California
The Model does not suggest opening a new expansion in Murrieta, California
City: Naperville, State: Illinois
The Model does not suggest opening a new expansion in Naperville, Illinois
City: New Haven, State: Connecticut
The Model suggests opening a new expansion in New Haven, Connecticut
City: Newport News, State: Virginia
The Model suggests opening a new expansion in Newport News, Virginia
City: North Charleston, State: South Carolina
The Model does not suggest opening a new expansion in North Charleston, South Carolina
City: Norwalk, State: California
The Model does not suggest opening a new expansion in Norwalk, California
City: Oceanside, State: California
The Model suggests opening a new expansion in Oceanside, California
City: Olathe, State: Kansas
The Model does not suggest opening a new expansion in Olathe, Kansas
City: Ontario, State: California
The Model suggests opening a new expansion in Ontario, California
City: Orange, State: California
The Model does not suggest opening a new expansion in Orange, California
City: Overland Park, State: Kansas
The Model suggests opening a new expansion in Overland Park, Kansas
City: Oxnard, State: California
The Model suggests opening a new expansion in Oxnard, California
City: Palm Bay, State: Florida
The Model does not suggest opening a new expansion in Palm Bay, Florida
City: Pasadena, State: California
The Model suggests opening a new expansion in Pasadena, California
No data found for City: Paterson, State: New Jersey
City: Pearland, State: Texas
The Model does not suggest opening a new expansion in Pearland, Texas
City: Peoria, State: Arizona
The Model suggests opening a new expansion in Peoria, Arizona
City: Pompano Beach, State: Florida
The Model does not suggest opening a new expansion in Pompano Beach, Florida
City: Port St. Lucie, State: Florida
The Model suggests opening a new expansion in Port St. Lucie, Florida
City: Providence, State: Rhode Island
The Model suggests opening a new expansion in Providence, Rhode Island
City: Pueblo, State: Colorado
The Model does not suggest opening a new expansion in Pueblo, Colorado
No data found for City: Rancho Cucamonga, State: California
City: Renton, State: Washington
The Model suggests opening a new expansion in Renton, Washington
City: Rialto, State: California
The Model does not suggest opening a new expansion in Rialto, California
City: Richardson, State: Texas
The Model does not suggest opening a new expansion in Richardson, Texas
City: Richmond, State: California
The Model does not suggest opening a new expansion in Richmond, California
City: Rochester, State: Minnesota
The Model does not suggest opening a new expansion in Rochester, Minnesota
City: Rochester, State: New York
The Model suggests opening a new expansion in Rochester, New York
No data found for City: Rockford, State: Illinois
City: Roseville, State: California
The Model does not suggest opening a new expansion in Roseville, California
City: Salt Lake City, State: Utah
The Model suggests opening a new expansion in Salt Lake City, Utah
City: San Angelo, State: Texas
The Model suggests opening a new expansion in San Angelo, Texas
City: San Bernardino, State: California
The Model suggests opening a new expansion in San Bernardino, California
City: San Mateo, State: California
The Model does not suggest opening a new expansion in San Mateo, California
City: Sandy Springs, State: Georgia
The Model does not suggest opening a new expansion in Sandy Springs, Georgia
City: Santa Clara, State: California
The Model does not suggest opening a new expansion in Santa Clara, California
City: Santa Clarita, State: California
The Model suggests opening a new expansion in Santa Clarita, California
City: Santa Maria, State: California
The Model does not suggest opening a new expansion in Santa Maria, California
City: Santa Rosa, State: California
The Model suggests opening a new expansion in Santa Rosa, California
City: Savannah, State: Georgia
The Model does not suggest opening a new expansion in Savannah, Georgia
City: Shreveport, State: Louisiana
The Model suggests opening a new expansion in Shreveport, Louisiana
City: Simi Valley, State: California
The Model does not suggest opening a new expansion in Simi Valley, California
City: Sioux Falls, State: South Dakota
The Model suggests opening a new expansion in Sioux Falls, South Dakota
City: South Bend, State: Indiana
The Model does not suggest opening a new expansion in South Bend, Indiana
City: Spokane, State: Washington
The Model suggests opening a new expansion in Spokane, Washington
City: Stamford, State: Connecticut
The Model suggests opening a new expansion in Stamford, Connecticut
City: Sterling Heights, State: Michigan
The Model does not suggest opening a new expansion in Sterling Heights, Michigan
City: Surprise, State: Arizona
The Model does not suggest opening a new expansion in Surprise, Arizona
City: Syracuse, State: New York
The Model does not suggest opening a new expansion in Syracuse, New York
City: Tacoma, State: Washington
The Model suggests opening a new expansion in Tacoma, Washington
City: Tallahassee, State: Florida
The Model suggests opening a new expansion in Tallahassee, Florida
City: Temecula, State: California
The Model does not suggest opening a new expansion in Temecula, California
No data found for City: Tempe, State: Arizona
City: Thornton, State: Colorado
The Model suggests opening a new expansion in Thornton, Colorado
No data found for City: Thousand Oaks, State: California
City: Topeka, State: Kansas
The Model does not suggest opening a new expansion in Topeka, Kansas
City: Tyler, State: Texas
The Model does not suggest opening a new expansion in Tyler, Texas
City: Vancouver, State: Washington
The Model suggests opening a new expansion in Vancouver, Washington
City: Ventura, State: California
The Model does not suggest opening a new expansion in Ventura, California
City: Visalia, State: California
The Model suggests opening a new expansion in Visalia, California
City: Vista, State: California
The Model does not suggest opening a new expansion in Vista, California
City: Waco, State: Texas
The Model does not suggest opening a new expansion in Waco, Texas
City: Warren, State: Michigan
The Model suggests opening a new expansion in Warren, Michigan
City: Waterbury, State: Connecticut
The Model does not suggest opening a new expansion in Waterbury, Connecticut
City: West Covina, State: California
The Model does not suggest opening a new expansion in West Covina, California
City: West Jordan, State: Utah
The Model does not suggest opening a new expansion in West Jordan, Utah
City: West Palm Beach, State: Florida
The Model does not suggest opening a new expansion in West Palm Beach, Florida
City: West Valley City, State: Utah
The Model suggests opening a new expansion in West Valley City, Utah
City: Wichita Falls, State: Texas
The Model does not suggest opening a new expansion in Wichita Falls, Texas
City: Woodbridge, State: New Jersey
The Model does not suggest opening a new expansion in Woodbridge, New Jersey
City: Worcester, State: Massachusetts
The Model suggests opening a new expansion in Worcester, Massachusetts
City: Yonkers, State: New York
The Model suggests opening a new expansion in Yonkers, New York
the number of suggestion for opening is  66
the number of suggestion for NOT opening is  74

In [ ]:
# Input City and State
input_city = 'Killeen'
input_state = 'Texas'

# Filter the DataFrame based on City and State
filtered_data = startups[(startups['City'] == input_city) & (startups['State'] == input_state) &(startups['New Expansion'] == 'Old')]

# Check if there's any matching data
if not filtered_data.empty:
    # Extract Marketing Spend, Profit, and ROMS values
    marketing_spend = filtered_data['Marketing Spend'].values[0]
    profit = filtered_data['Profit'].values[0]
    roms = filtered_data['ROMS'].values[0]
    print(f"Marketing Spend: {marketing_spend}")
    print(f"Profit: {profit}")
    print(f"ROMS: {roms}")

    if profit > 40053 and roms > 1274:
        print(f"The Model  suggests opening a new expansion in {input_city} city and {input_state} state ")
    else:
        print(f"The Model does not suggest opening a new expansion in {input_city} city and {input_state} state ")

else:
    print("Enter The Data Right")

In [76]:
import tkinter as tk
from tkinter import ttk
# Function to handle the button click
def analyze_data():
    input_city = city_entry.get()
    input_state = state_entry.get()

    # Filter the DataFrame based on City, State, and New Expansion
    filtered_data = startups[(startups['City'] == input_city) & (startups['State'] == input_state) & (startups['New Expansion'] == 'Old')]

    # Check if there's any matching data
    if not filtered_data.empty:
        # Extract Marketing Spend, Profit, and ROMS values
        marketing_spend = filtered_data['Marketing Spend'].values[0]
        profit = filtered_data['Profit'].values[0]
        roms = filtered_data['ROMS'].values[0]

        result_label.config(text=f"Marketing Spend: {marketing_spend}\nProfit: {profit}\nROMS: {roms}")

        if profit > 40053 and roms > 1274:
            result_label.config(text=result_label.cget("text") + f"\nThe Model suggests opening a new expansion in {input_city}, {input_state}")
        else:
            result_label.config(text=result_label.cget("text") + f"\nThe Model does not suggest opening a new expansion in {input_city}, {input_state}")
    else:
        result_label.config(text="Enter The Data Right")

# Create the GUI window
root = tk.Tk()
root.title("Store Analysis")

# Create and pack labels and entry fields
city_label = ttk.Label(root, text="Enter City:")
city_label.pack()
city_entry = ttk.Entry(root)
city_entry.pack()

state_label = ttk.Label(root, text="Enter State:")
state_label.pack()
state_entry = ttk.Entry(root)
state_entry.pack()

# Create and pack the Analyze button
analyze_button = ttk.Button(root, text="Analyze", command=analyze_data)
analyze_button.pack()

# Create and pack the result label
result_label = ttk.Label(root, text="")
result_label.pack()

# Start the GUI event loop
root.mainloop()